(define agent-name "mcp-test")
(define agent-provider 'ollama)
(define agent-model "demo")
(define agent-base-url "http://127.0.0.1:11434")
(define agent-api-key-environment #f)
(define agent-stream? #t)
(define agent-thinking #f)
(define agent-max-tool-rounds 1)
(define agent-compaction-threshold 12)
(define agent-compaction-keep-recent 4)
(define agent-system-prompt "MCP bridge fixture")
(define agent-tools '(read rg))
(define agent-shell-policy 'deny)
(define (agent-select-context text) '())
(define (agent-transform-user text) text)
(define (agent-demo-response text) (string-append "[mcp-test] " text))
