(define-module (live-agent json)
  #:use-module (ice-9 format)
  #:use-module (ice-9 textual-ports)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-9)
  #:export (json-object
            json-object?
            json-object-entries
            json-object-ref
            json-array
            json-array?
            json-array-items
            json-null
            json-read
            json-write))

(define-record-type <json-object>
  (%json-object entries)
  json-object?
  (entries json-object-entries))

(define-record-type <json-array>
  (%json-array items)
  json-array?
  (items json-array-items))

(define json-null (list 'json-null))
(define missing (list 'missing))

(define (json-object . entries)
  (%json-object entries))

(define (json-array . items)
  (%json-array items))

(define* (json-object-ref object key #:optional (fallback missing))
  (let ((entry (find (lambda (pair) (string=? (car pair) key))
                     (json-object-entries object))))
    (cond
     (entry (cdr entry))
     ((eq? fallback missing) (error "JSON object has no key" key))
     (else fallback))))

(define (write-json-string value port)
  (write-char #\" port)
  (string-for-each
   (lambda (character)
     (case character
       ((#\") (display "\\\"" port))
       ((#\\) (display "\\\\" port))
       ((#\backspace) (display "\\b" port))
       ((#\page) (display "\\f" port))
       ((#\newline) (display "\\n" port))
       ((#\return) (display "\\r" port))
       ((#\tab) (display "\\t" port))
       (else
        (if (< (char->integer character) 32)
            (format port "\\u~4,'0x" (char->integer character))
            (write-char character port)))))
   value)
  (write-char #\" port))

(define (write-json value port)
  (cond
   ((json-object? value)
    (write-char #\{ port)
    (let loop ((entries (json-object-entries value)) (first? #t))
      (unless (null? entries)
        (unless first? (write-char #\, port))
        (write-json-string (caar entries) port)
        (write-char #\: port)
        (write-json (cdar entries) port)
        (loop (cdr entries) #f)))
    (write-char #\} port))
   ((json-array? value)
    (write-char #\[ port)
    (let loop ((items (json-array-items value)) (first? #t))
      (unless (null? items)
        (unless first? (write-char #\, port))
        (write-json (car items) port)
        (loop (cdr items) #f)))
    (write-char #\] port))
   ((string? value) (write-json-string value port))
   ((number? value) (display (number->string value) port))
   ((eq? value #t) (display "true" port))
   ((eq? value #f) (display "false" port))
   ((eq? value json-null) (display "null" port))
   (else (error "cannot encode value as JSON" value))))

(define (json-write value)
  (call-with-output-string (lambda (port) (write-json value port))))

(define (json-read text)
  (let ((position 0)
        (length (string-length text)))
    (define (peek)
      (and (< position length) (string-ref text position)))
    (define (take!)
      (let ((character (peek)))
        (when character (set! position (+ position 1)))
        character))
    (define (skip-space!)
      (while (and (peek) (char-whitespace? (peek))) (take!)))
    (define (expect! expected)
      (let ((actual (take!)))
        (unless (and actual (char=? actual expected))
          (error "unexpected JSON character" expected actual position))))
    (define (read-hex4!)
      (when (> (+ position 4) length)
        (error "incomplete JSON unicode escape" position))
      (let* ((digits (substring text position (+ position 4)))
             (value (string->number digits 16)))
        (unless value (error "invalid JSON unicode escape" digits))
        (set! position (+ position 4))
        value))
    (define (read-unicode!)
      (let ((first (read-hex4!)))
        (if (and (<= #xd800 first) (<= first #xdbff)
                 (<= (+ position 6) length)
                 (char=? (string-ref text position) #\\)
                 (char=? (string-ref text (+ position 1)) #\u))
            (begin
              (set! position (+ position 2))
              (let ((second (read-hex4!)))
                (unless (and (<= #xdc00 second) (<= second #xdfff))
                  (error "invalid JSON surrogate pair" first second))
                (+ #x10000
                   (* (- first #xd800) #x400)
                   (- second #xdc00))))
            first)))
    (define (read-string!)
      (expect! #\")
      (call-with-output-string
       (lambda (port)
         (let loop ()
           (let ((character (take!)))
             (cond
              ((not character) (error "unterminated JSON string"))
              ((char=? character #\") #t)
              ((char=? character #\\)
               (let ((escape (take!)))
                 (unless escape (error "unterminated JSON escape"))
                 (case escape
                   ((#\" #\\ #\/) (write-char escape port))
                   ((#\b) (write-char #\backspace port))
                   ((#\f) (write-char #\page port))
                   ((#\n) (write-char #\newline port))
                   ((#\r) (write-char #\return port))
                   ((#\t) (write-char #\tab port))
                   ((#\u) (write-char (integer->char (read-unicode!)) port))
                   (else (error "invalid JSON escape" escape)))
                 (loop)))
              (else
               (write-char character port)
               (loop))))))))
    (define (read-number!)
      (let ((start position))
        (while (and (peek)
                    (or (char-numeric? (peek))
                        (memv (peek) '(#\- #\+ #\. #\e #\E))))
          (take!))
        (let* ((token (substring text start position))
               (number (string->number token)))
          (unless number (error "invalid JSON number" token))
          number)))
    (define (read-literal! literal value)
      (let ((end (+ position (string-length literal))))
        (unless (and (<= end length)
                     (string=? (substring text position end) literal))
          (error "invalid JSON literal" position))
        (set! position end)
        value))
    (define (read-array!)
      (expect! #\[)
      (skip-space!)
      (if (and (peek) (char=? (peek) #\]))
          (begin (take!) (%json-array '()))
          (let loop ((items '()))
            (let ((value (read-value!)))
              (skip-space!)
              (case (take!)
                ((#\,) (skip-space!) (loop (cons value items)))
                ((#\]) (%json-array (reverse (cons value items))))
                (else (error "expected comma or closing bracket" position)))))))
    (define (read-object!)
      (expect! #\{)
      (skip-space!)
      (if (and (peek) (char=? (peek) #\}))
          (begin (take!) (%json-object '()))
          (let loop ((entries '()))
            (unless (and (peek) (char=? (peek) #\"))
              (error "expected JSON object key" position))
            (let ((key (read-string!)))
              (skip-space!)
              (expect! #\:)
              (skip-space!)
              (let ((value (read-value!)))
                (skip-space!)
                (case (take!)
                  ((#\,) (skip-space!) (loop (cons (cons key value) entries)))
                  ((#\}) (%json-object (reverse (cons (cons key value) entries))))
                  (else (error "expected comma or closing brace" position))))))))
    (define (read-value!)
      (skip-space!)
      (let ((character (peek)))
        (cond
         ((not character) (error "unexpected end of JSON"))
         ((char=? character #\") (read-string!))
         ((char=? character #\{) (read-object!))
         ((char=? character #\[) (read-array!))
         ((or (char-numeric? character) (char=? character #\-)) (read-number!))
         ((char=? character #\t) (read-literal! "true" #t))
         ((char=? character #\f) (read-literal! "false" #f))
         ((char=? character #\n) (read-literal! "null" json-null))
         (else (error "unexpected JSON value" character position)))))
    (let ((value (read-value!)))
      (skip-space!)
      (unless (= position length)
        (error "trailing content after JSON value" position))
      value)))
